version: '3.9'

services:
  backend:
    container_name: rest-api-server
    restart: unless-stopped
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    networks:
      - spring-cloud-network
    depends_on:
      - db
########################################################################################################################
  frontend:
    container_name: react-frontend-client
    restart: unless-stopped
    build: ./client
    ports:
      - '3000:3000'
    networks:
      - spring-cloud-network
    depends_on:
      - backend
########################################################################################################################
  db:
    container_name: postgres-db
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'fe8fs2tw'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'dbTW1991'
    ports:
      - '5432:5432'
    volumes:
      - '../../../ro:/ro:ro'
      - '../../../rw:/rw'
      - '../../../Downloads:/dl:ro'
      - '../.data/pg10:/var/lib/postgresql/data'
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge